In [13]:
import numpy as np

In [14]:
#1
# np.intersect function to find intersection. 
# numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)
# https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a, b)

array([2, 4])

In [15]:
#2
# Arrange arr from 1 to 16
arr = np.arange(1,16)
# Reshpae arr into a 3x5 array
arr = np.reshape(arr, (3,5))
# Take transpose of arr
arr = arr.T
arr1 = arr
print(arr)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [16]:
#3
# Take transpose of arr again, so output is the ordered correctly
arr = arr.T
# Flatten the now 3x5 array by use of flatten() function
arr =arr.flatten()
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [17]:
#4
print(arr1)
# Take arr1 transpose and reshape into a 3 dimensional array
arr2 = arr1.T.reshape(3,5,1)
print(arr2)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


In [18]:
#5
# Reverse of question 4
# Take transpose of arr2 and reshape to a 3x5 array
print(arr2.T.reshape(1,5,3))

[[[ 1  6 11]
  [ 2  7 12]
  [ 3  8 13]
  [ 4  9 14]
  [ 5 10 15]]]


In [19]:
# 6
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
# Find the intersection between a and b
c = np.intersect1d(a,b)

# Use numpy setdiff1d() function to remove from a the items in the intersection of a and b, c
a = np.setdiff1d(a, c)
print(a)


[ 1  7  8 15]


In [21]:
import pandas 
import numpy as np
np.set_printoptions(suppress = True)
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/brianlivian/M6-Data/main/Module6_Data.csv?token=ASTO4MKQQPQGDLUXZHE7RQDAHPD2S').to_numpy()
type(nyc_water)


numpy.ndarray

In [22]:
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

In [23]:
#7
print('The maximum yearly consumption of water in millions pers gallons is ' + str(np.max(nyc_water[:, 2])))

print('There are ' + str(np.shape(nyc_water[:, 0])) + ' calendar years in this dataset')

print('The mean per capita water consumption is ' + str(np.mean(nyc_water[:, 3])))

print('The standard deviation for per capita water consumption is ' + str(np.std(nyc_water[:,3])))

pop_diff = np.diff(nyc_water[:,1])
print(pop_diff)

The maximum yearly consumption of water in millions pers gallons is 1512.0
There are (39,) calendar years in this dataset
The mean per capita water consumption is 160.30769230769232
The standard deviation for per capita water consumption is 31.51894330370624
[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
